//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainPDO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GrafolitPDOEntities : DbContext
    {
        public GrafolitPDOEntities()
            : base("name=GrafolitPDOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Osebe_PDO> Osebe_PDO { get; set; }
        public DbSet<OsebeNadrejeni_PDO> OsebeNadrejeni_PDO { get; set; }
        public DbSet<StatusPovprasevanja> StatusPovprasevanja { get; set; }
        public DbSet<StrankaZaposleni_PDO> StrankaZaposleni_PDO { get; set; }
        public DbSet<SystemMessageEvents_PDO> SystemMessageEvents_PDO { get; set; }
        public DbSet<TipStranka_PDO> TipStranka_PDO { get; set; }
        public DbSet<Vloga_PDO> Vloga_PDO { get; set; }
        public DbSet<Nastavitve> Nastavitve { get; set; }
        public DbSet<Jeziki> Jeziki { get; set; }
        public DbSet<Oddelek> Oddelek { get; set; }
        public DbSet<KontaktnaOseba_PDO> KontaktnaOseba_PDO { get; set; }
        public DbSet<Stranka_PDO> Stranka_PDO { get; set; }
        public DbSet<PovprasevanjePozicija> PovprasevanjePozicija { get; set; }
        public DbSet<PovprasevanjePozicijaArtikel> PovprasevanjePozicijaArtikel { get; set; }
        public DbSet<NarociloPozicija_PDO> NarociloPozicija_PDO { get; set; }
        public DbSet<Narocilo_PDO> Narocilo_PDO { get; set; }
        public DbSet<Povprasevanje> Povprasevanje { get; set; }
        public DbSet<SystemEmailMessage_PDO> SystemEmailMessage_PDO { get; set; }
    
        [EdmFunction("GrafolitPDOEntities", "GetArtikelBySearchStr")]
        public virtual IQueryable<GetArtikelBySearchStr_Result> GetArtikelBySearchStr(string searchStr)
        {
            var searchStrParameter = searchStr != null ?
                new ObjectParameter("SearchStr", searchStr) :
                new ObjectParameter("SearchStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetArtikelBySearchStr_Result>("[GrafolitPDOEntities].[GetArtikelBySearchStr](@SearchStr)", searchStrParameter);
        }
    
        [EdmFunction("GrafolitPDOEntities", "GetBuyerList")]
        public virtual IQueryable<string> GetBuyerList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[GrafolitPDOEntities].[GetBuyerList]()");
        }
    
        [EdmFunction("GrafolitPDOEntities", "GetCategoryList")]
        public virtual IQueryable<string> GetCategoryList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[GrafolitPDOEntities].[GetCategoryList]()");
        }
    
        [EdmFunction("GrafolitPDOEntities", "GetSuplierBySearchStr")]
        public virtual IQueryable<string> GetSuplierBySearchStr(string searchStr)
        {
            var searchStrParameter = searchStr != null ?
                new ObjectParameter("SearchStr", searchStr) :
                new ObjectParameter("SearchStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[GrafolitPDOEntities].[GetSuplierBySearchStr](@SearchStr)", searchStrParameter);
        }
    
        public virtual int DodajPantheonDokument(string p_xParameters, ObjectParameter p_cExportPath, ObjectParameter p_cKey, ObjectParameter p_cError)
        {
            var p_xParametersParameter = p_xParameters != null ?
                new ObjectParameter("p_xParameters", p_xParameters) :
                new ObjectParameter("p_xParameters", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajPantheonDokument", p_xParametersParameter, p_cExportPath, p_cKey, p_cError);
        }
    
        [EdmFunction("GrafolitPDOEntities", "GetPantheonUsers")]
        public virtual IQueryable<GetPantheonUsers_Result> GetPantheonUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetPantheonUsers_Result>("[GrafolitPDOEntities].[GetPantheonUsers]()");
        }
    
        [EdmFunction("GrafolitPDOEntities", "GetArtikelByName")]
        public virtual IQueryable<GetArtikelByName_Result2> GetArtikelByName(string supplier, string name)
        {
            var supplierParameter = supplier != null ?
                new ObjectParameter("Supplier", supplier) :
                new ObjectParameter("Supplier", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetArtikelByName_Result2>("[GrafolitPDOEntities].[GetArtikelByName](@Supplier, @Name)", supplierParameter, nameParameter);
        }
    }
}
