//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainPDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jeziki
    {
        public Jeziki()
        {
            this.Stranka_PDO = new HashSet<Stranka_PDO>();
        }
    
        public int JezikID { get; set; }
        public string Koda { get; set; }
        public string Naziv { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
    
        public virtual ICollection<Stranka_PDO> Stranka_PDO { get; set; }
    }
}
