//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainPDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oddelek
    {
        public Oddelek()
        {
            this.PovprasevanjePozicijaArtikel = new HashSet<PovprasevanjePozicijaArtikel>();
            this.NarociloPozicija_PDO = new HashSet<NarociloPozicija_PDO>();
            this.Narocilo_PDO = new HashSet<Narocilo_PDO>();
            this.Povprasevanje = new HashSet<Povprasevanje>();
        }
    
        public int OddelekID { get; set; }
        public string Koda { get; set; }
        public string Naziv { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
    
        public virtual ICollection<PovprasevanjePozicijaArtikel> PovprasevanjePozicijaArtikel { get; set; }
        public virtual ICollection<NarociloPozicija_PDO> NarociloPozicija_PDO { get; set; }
        public virtual ICollection<Narocilo_PDO> Narocilo_PDO { get; set; }
        public virtual ICollection<Povprasevanje> Povprasevanje { get; set; }
    }
}
