//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainPDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Povprasevanje
    {
        public Povprasevanje()
        {
            this.PovprasevanjePozicija = new HashSet<PovprasevanjePozicija>();
        }
    
        public int PovprasevanjeID { get; set; }
        public int KupecID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> NarociloID { get; set; }
        public string KupecNaziv_P { get; set; }
        public string Naziv { get; set; }
        public string PovprasevanjeStevilka { get; set; }
        public Nullable<System.DateTime> DatumOddajePovprasevanja { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
        public Nullable<System.DateTime> tsUpdate { get; set; }
        public Nullable<int> tsUpdateUserID { get; set; }
        public Nullable<bool> Zakleni { get; set; }
        public Nullable<int> ZaklenilUporabnik { get; set; }
        public Nullable<System.DateTime> DatumPredvideneDobave { get; set; }
        public Nullable<int> PovprasevajneOddal { get; set; }
        public Nullable<bool> NotSendPDFAndEmailsToSupplier { get; set; }
        public string Dobavitelji { get; set; }
        public string OpombaNarocilnica { get; set; }
        public Nullable<int> OddelekID { get; set; }
        public string Narocila { get; set; }
    
        public virtual Oddelek Oddelek { get; set; }
        public virtual Osebe_PDO Osebe_PDO { get; set; }
        public virtual Stranka_PDO Stranka_PDO { get; set; }
        public virtual ICollection<PovprasevanjePozicija> PovprasevanjePozicija { get; set; }
        public virtual StatusPovprasevanja StatusPovprasevanja { get; set; }
    }
}
