//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainPDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PovprasevanjePozicijaArtikel
    {
        public int PovprasevanjePozicijaArtikelID { get; set; }
        public int PovprasevanjePozicijaID { get; set; }
        public string KategorijaNaziv { get; set; }
        public string Naziv { get; set; }
        public Nullable<decimal> Kolicina1 { get; set; }
        public string EnotaMere1 { get; set; }
        public Nullable<decimal> Kolicina2 { get; set; }
        public string EnotaMere2 { get; set; }
        public string Opombe { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
        public Nullable<System.DateTime> tsUpdate { get; set; }
        public Nullable<int> tsUpdateUserID { get; set; }
        public string Ident { get; set; }
        public string IzbraniArtikelNaziv_P { get; set; }
        public Nullable<decimal> ArtikelCena { get; set; }
        public Nullable<decimal> KolicinavKG { get; set; }
        public string EnotaMere { get; set; }
        public Nullable<decimal> Rabat { get; set; }
        public string OpombaNarocilnica { get; set; }
        public Nullable<int> OddelekID { get; set; }
        public Nullable<bool> PrikaziKupca { get; set; }
        public Nullable<bool> IzbranArtikel { get; set; }
        public Nullable<System.DateTime> DatumDobavePos { get; set; }
        public Nullable<int> DobaviteljID { get; set; }
        public string DobaviteljNaziv_PA { get; set; }
        public Nullable<decimal> KolicinaVPOL { get; set; }
        public string NarEnotaMere2 { get; set; }
        public string Poreklo { get; set; }
    
        public virtual Oddelek Oddelek { get; set; }
        public virtual PovprasevanjePozicija PovprasevanjePozicija { get; set; }
        public virtual Stranka_PDO Stranka_PDO { get; set; }
    }
}
