//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainPDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PovprasevanjePozicija
    {
        public PovprasevanjePozicija()
        {
            this.PovprasevanjePozicijaArtikel = new HashSet<PovprasevanjePozicijaArtikel>();
            this.NarociloPozicija_PDO = new HashSet<NarociloPozicija_PDO>();
        }
    
        public int PovprasevanjePozicijaID { get; set; }
        public int PovprasevanjeID { get; set; }
        public int DobaviteljID { get; set; }
        public string DobaviteljNaziv_P { get; set; }
        public string DobaviteljKontaktOsebe { get; set; }
        public string DobaviteljID_P { get; set; }
        public string Artikli { get; set; }
        public Nullable<bool> KupecViden { get; set; }
        public Nullable<System.DateTime> DatumPredvideneDobave { get; set; }
        public string PotDokumenta { get; set; }
        public string Opomba { get; set; }
        public string EmailBody { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
        public Nullable<System.DateTime> tsUpdate { get; set; }
        public Nullable<int> tsUpdateUserID { get; set; }
        public string ObvesceneOsebe { get; set; }
    
        public virtual Stranka_PDO Stranka_PDO { get; set; }
        public virtual ICollection<PovprasevanjePozicijaArtikel> PovprasevanjePozicijaArtikel { get; set; }
        public virtual Povprasevanje Povprasevanje { get; set; }
        public virtual ICollection<NarociloPozicija_PDO> NarociloPozicija_PDO { get; set; }
    }
}
