//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainPDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusPovprasevanja
    {
        public StatusPovprasevanja()
        {
            this.Narocilo_PDO = new HashSet<Narocilo_PDO>();
            this.Povprasevanje = new HashSet<Povprasevanje>();
        }
    
        public int StatusPovprasevanjaID { get; set; }
        public string Koda { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public Nullable<int> tsIDOseba { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<System.DateTime> tsUpdate { get; set; }
        public Nullable<int> tsUpdateUserID { get; set; }
    
        public virtual ICollection<Narocilo_PDO> Narocilo_PDO { get; set; }
        public virtual ICollection<Povprasevanje> Povprasevanje { get; set; }
    }
}
