//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemEmailMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemEmailMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatabaseWebService.Resources.SystemEmailMessageResource", typeof(SystemEmailMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo sporočilo.
        /// </summary>
        public static string res_01 {
            get {
                return ResourceManager.GetString("res_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padec prodaje.
        /// </summary>
        public static string res_02 {
            get {
                return ResourceManager.GetString("res_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov dogodek na stranki.
        /// </summary>
        public static string res_03 {
            get {
                return ResourceManager.GetString("res_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opozorilo o manjkajočih podatkih na dogodku (%Tip%).
        /// </summary>
        public static string res_04 {
            get {
                return ResourceManager.GetString("res_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebna odobritev na odpoklicu.
        /// </summary>
        public static string res_05 {
            get {
                return ResourceManager.GetString("res_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprememba status na odpoklicu.
        /// </summary>
        public static string res_06 {
            get {
                return ResourceManager.GetString("res_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafo Lit - Vabilo k oddaji cene.
        /// </summary>
        public static string res_07 {
            get {
                return ResourceManager.GetString("res_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafo Lit - Čestitamo bili ste izbrani za našega prevoznika.
        /// </summary>
        public static string res_08 {
            get {
                return ResourceManager.GetString("res_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obveščamo vas, da ste bili izbrani na podlagi prijavljene cene, dne .
        /// </summary>
        public static string res_09 {
            get {
                return ResourceManager.GetString("res_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obveščamo vas, da žal niste bili izbrani na podlagi prijavljene cene, dne .
        /// </summary>
        public static string res_10 {
            get {
                return ResourceManager.GetString("res_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafo Lit - Žal niste bili izbrani.
        /// </summary>
        public static string res_11 {
            get {
                return ResourceManager.GetString("res_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpoklici - Prevoznik izbran!.
        /// </summary>
        public static string res_12 {
            get {
                return ResourceManager.GetString("res_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpoklici - Poslana povpraševanje brez ponudbe.
        /// </summary>
        public static string res_13 {
            get {
                return ResourceManager.GetString("res_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obveščamo vas, da je bil izbran prevoznik .
        /// </summary>
        public static string res_14 {
            get {
                return ResourceManager.GetString("res_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpoklici - Poslano povpraševajne za prevoznika.
        /// </summary>
        public static string res_15 {
            get {
                return ResourceManager.GetString("res_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošiljamo vam povpraševanje za prevoz blaga..
        /// </summary>
        public static string res_16 {
            get {
                return ResourceManager.GetString("res_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S klikom na spodnji gumb odprete obrazec za prijavo cene za prevoz blaga, ki vsebuje tudi podatke o prevozu..
        /// </summary>
        public static string res_17 {
            get {
                return ResourceManager.GetString("res_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošiljamo vam naročilnico za prevoz.
        /// </summary>
        public static string res_18 {
            get {
                return ResourceManager.GetString("res_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafo Lit - Inquiry for material.
        /// </summary>
        public static string res_19 {
            get {
                return ResourceManager.GetString("res_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obvestilo o poslanem povpraševanju.
        /// </summary>
        public static string res_20 {
            get {
                return ResourceManager.GetString("res_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obvestilo za administratorja sistema.
        /// </summary>
        public static string res_21 {
            get {
                return ResourceManager.GetString("res_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošiljamo vam naročilnico za povpraševanje.
        /// </summary>
        public static string res_22 {
            get {
                return ResourceManager.GetString("res_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obvestilo o potrebnem odprtju nove šifre.
        /// </summary>
        public static string res_23 {
            get {
                return ResourceManager.GetString("res_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obvestilo o generiranju naročilnice.
        /// </summary>
        public static string res_24 {
            get {
                return ResourceManager.GetString("res_24", resourceCulture);
            }
        }
    }
}
