//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationExceptionError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationExceptionError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatabaseWebService.Resources.ValidationExceptionError", typeof(ValidationExceptionError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign in \r\n Username or password was not correct! \r\n Please try again.
        /// </summary>
        public static string res_01 {
            get {
                return ResourceManager.GetString("res_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no clients in database..
        /// </summary>
        public static string res_02 {
            get {
                return ResourceManager.GetString("res_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client with specific ID does not exist.
        /// </summary>
        public static string res_03 {
            get {
                return ResourceManager.GetString("res_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting client failed. Client with specific id does not exist.
        /// </summary>
        public static string res_04 {
            get {
                return ResourceManager.GetString("res_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting client&apos;s plan failed. Plan with specific id does not exist.
        /// </summary>
        public static string res_05 {
            get {
                return ResourceManager.GetString("res_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository failed to retrieve data.
        /// </summary>
        public static string res_06 {
            get {
                return ResourceManager.GetString("res_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository failed to delete data.
        /// </summary>
        public static string res_07 {
            get {
                return ResourceManager.GetString("res_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository failed to save data.
        /// </summary>
        public static string res_08 {
            get {
                return ResourceManager.GetString("res_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model was found for saving.
        /// </summary>
        public static string res_09 {
            get {
                return ResourceManager.GetString("res_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting client&apos;s contact person failed. Person with specific id does not exist.
        /// </summary>
        public static string res_10 {
            get {
                return ResourceManager.GetString("res_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Categories in database.
        /// </summary>
        public static string res_11 {
            get {
                return ResourceManager.GetString("res_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Employees in database.
        /// </summary>
        public static string res_12 {
            get {
                return ResourceManager.GetString("res_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting ClientEmployee failed. Specific id does not exist.
        /// </summary>
        public static string res_13 {
            get {
                return ResourceManager.GetString("res_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientEmployee does note exist.
        /// </summary>
        public static string res_14 {
            get {
                return ResourceManager.GetString("res_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no events in database.
        /// </summary>
        public static string res_15 {
            get {
                return ResourceManager.GetString("res_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no employees by specific role id.
        /// </summary>
        public static string res_16 {
            get {
                return ResourceManager.GetString("res_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no event statuses.
        /// </summary>
        public static string res_17 {
            get {
                return ResourceManager.GetString("res_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting event failed. Event with specific id does not exist..
        /// </summary>
        public static string res_18 {
            get {
                return ResourceManager.GetString("res_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting message failed. Message with specific id does not exist..
        /// </summary>
        public static string res_19 {
            get {
                return ResourceManager.GetString("res_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Device failed. Specific id does not exist..
        /// </summary>
        public static string res_20 {
            get {
                return ResourceManager.GetString("res_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee with specific ID does not exist.
        /// </summary>
        public static string res_21 {
            get {
                return ResourceManager.GetString("res_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting employee failed. Employee with specific id does not exist.
        /// </summary>
        public static string res_22 {
            get {
                return ResourceManager.GetString("res_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no roles in database.
        /// </summary>
        public static string res_23 {
            get {
                return ResourceManager.GetString("res_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting ClientCategorie failed. Specific id does not exist.
        /// </summary>
        public static string res_24 {
            get {
                return ResourceManager.GetString("res_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data for specific charts.
        /// </summary>
        public static string res_25 {
            get {
                return ResourceManager.GetString("res_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no supervisors for this employee.
        /// </summary>
        public static string res_26 {
            get {
                return ResourceManager.GetString("res_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard repository error.
        /// </summary>
        public static string res_27 {
            get {
                return ResourceManager.GetString("res_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create order document in Pantheon Error.
        /// </summary>
        public static string res_28 {
            get {
                return ResourceManager.GetString("res_28", resourceCulture);
            }
        }
    }
}
