//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avtomatika
    {
        public int AvtomatikaID { get; set; }
        public int OsebaID { get; set; }
        public int Status { get; set; }
        public int StopnjaNadrejenega { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public int DogodekID { get; set; }
    
        public virtual Osebe Osebe { get; set; }
        public virtual Dogodek Dogodek { get; set; }
    }
}
