//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogodekSestanek
    {
        public int DogodekSestanekID { get; set; }
        public int DogodekID { get; set; }
        public string Tip { get; set; }
        public string Opis { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
    
        public virtual Dogodek Dogodek { get; set; }
    }
}
