//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancniDashboard
    {
        public Nullable<System.DateTime> Timestmp { get; set; }
        public int FinancniDashboardID { get; set; }
        public Nullable<decimal> Dobavitelji { get; set; }
        public Nullable<decimal> Kupci { get; set; }
        public Nullable<decimal> Zaloga { get; set; }
        public Nullable<decimal> Investicije { get; set; }
        public Nullable<decimal> Investicijsko_vzdrzevanje { get; set; }
        public Nullable<decimal> Krediti { get; set; }
        public Nullable<decimal> Dobicek { get; set; }
        public Nullable<decimal> Skupaj { get; set; }
        public Nullable<int> StDniKupci { get; set; }
        public Nullable<int> StDniDobavitelji { get; set; }
    }
}
