//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzpisGrafa
    {
        public int IzpisGrafaID { get; set; }
        public int StrankaID { get; set; }
        public int KategorijaID { get; set; }
        public Nullable<int> Obdobje { get; set; }
        public Nullable<int> Tip { get; set; }
        public string EnotaMere { get; set; }
        public string Opis { get; set; }
        public Nullable<decimal> Vrednost { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        public virtual Kategorija Kategorija { get; set; }
        public virtual Stranka Stranka { get; set; }
    }
}
