//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorija
    {
        public Kategorija()
        {
            this.Dogodek = new HashSet<Dogodek>();
            this.Nadzor = new HashSet<Nadzor>();
            this.PlanStranka = new HashSet<PlanStranka>();
            this.StrankaKategorija = new HashSet<StrankaKategorija>();
            this.IzpisGrafa = new HashSet<IzpisGrafa>();
        }
    
        public int idKategorija { get; set; }
        public string Koda { get; set; }
        public string Naziv { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
    
        public virtual ICollection<Dogodek> Dogodek { get; set; }
        public virtual ICollection<Nadzor> Nadzor { get; set; }
        public virtual ICollection<PlanStranka> PlanStranka { get; set; }
        public virtual ICollection<StrankaKategorija> StrankaKategorija { get; set; }
        public virtual ICollection<IzpisGrafa> IzpisGrafa { get; set; }
    }
}
