//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OsebeNadrejeni
    {
        public int OsebeNadrejeniID { get; set; }
        public int idOseba { get; set; }
        public int idNadrejeni { get; set; }
        public string Opomba { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDosebe { get; set; }
    
        public virtual Osebe Osebe { get; set; }
        public virtual Osebe Osebe1 { get; set; }
    }
}
