//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osebe
    {
        public Osebe()
        {
            this.Dogodek = new HashSet<Dogodek>();
            this.Dogodek1 = new HashSet<Dogodek>();
            this.Nadzor = new HashSet<Nadzor>();
            this.StrankaZaposleni = new HashSet<StrankaZaposleni>();
            this.Avtomatika = new HashSet<Avtomatika>();
            this.OsebeNadrejeni = new HashSet<OsebeNadrejeni>();
            this.OsebeNadrejeni1 = new HashSet<OsebeNadrejeni>();
        }
    
        public int idOsebe { get; set; }
        public Nullable<int> idVloga { get; set; }
        public string Ime { get; set; }
        public string Priimek { get; set; }
        public string Naslov { get; set; }
        public Nullable<System.DateTime> DatumRojstva { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DatumZaposlitve { get; set; }
        public string UporabniskoIme { get; set; }
        public string Geslo { get; set; }
        public string TelefonGSM { get; set; }
        public Nullable<int> Zunanji { get; set; }
        public string DelovnoMesto { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
        public string ProfileImage { get; set; }
    
        public virtual ICollection<Dogodek> Dogodek { get; set; }
        public virtual ICollection<Dogodek> Dogodek1 { get; set; }
        public virtual ICollection<Nadzor> Nadzor { get; set; }
        public virtual Vloga Vloga { get; set; }
        public virtual ICollection<StrankaZaposleni> StrankaZaposleni { get; set; }
        public virtual ICollection<Avtomatika> Avtomatika { get; set; }
        public virtual ICollection<OsebeNadrejeni> OsebeNadrejeni { get; set; }
        public virtual ICollection<OsebeNadrejeni> OsebeNadrejeni1 { get; set; }
    }
}
