//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stranka
    {
        public Stranka()
        {
            this.Dogodek = new HashSet<Dogodek>();
            this.KontaktneOsebe = new HashSet<KontaktneOsebe>();
            this.Nadzor = new HashSet<Nadzor>();
            this.StrankaZaposleni = new HashSet<StrankaZaposleni>();
            this.PlanStranka = new HashSet<PlanStranka>();
            this.Naprava = new HashSet<Naprava>();
            this.StrankaKategorija = new HashSet<StrankaKategorija>();
            this.IzpisGrafa = new HashSet<IzpisGrafa>();
        }
    
        public int idStranka { get; set; }
        public string KodaStranke { get; set; }
        public string NazivPrvi { get; set; }
        public string NazivDrugi { get; set; }
        public string Naslov { get; set; }
        public string StevPoste { get; set; }
        public string NazivPoste { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string FAX { get; set; }
        public string InternetniNalov { get; set; }
        public string KontaktnaOseba { get; set; }
        public string RokPlacila { get; set; }
        public string TRR { get; set; }
        public string DavcnaStev { get; set; }
        public string MaticnaStev { get; set; }
        public string RangStranke { get; set; }
        public string StatusDomacTuji { get; set; }
        public string Zavezanec_DA_NE { get; set; }
        public string IdentifikacijskaStev { get; set; }
        public string Clan_EU { get; set; }
        public string BIC { get; set; }
        public string KodaPlacila { get; set; }
        public string StatusKupecDobavitelj { get; set; }
        public string DrzavaStranke { get; set; }
        public string Neaktivna { get; set; }
        public Nullable<int> GenerirajERacun { get; set; }
        public Nullable<int> JavniZavod { get; set; }
        public Nullable<int> SecondID { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
    
        public virtual ICollection<Dogodek> Dogodek { get; set; }
        public virtual ICollection<KontaktneOsebe> KontaktneOsebe { get; set; }
        public virtual ICollection<Nadzor> Nadzor { get; set; }
        public virtual ICollection<StrankaZaposleni> StrankaZaposleni { get; set; }
        public virtual ICollection<PlanStranka> PlanStranka { get; set; }
        public virtual ICollection<Naprava> Naprava { get; set; }
        public virtual ICollection<StrankaKategorija> StrankaKategorija { get; set; }
        public virtual ICollection<IzpisGrafa> IzpisGrafa { get; set; }
    }
}
