//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AktivnostUporabnika
    {
        public int AktivnostUporabnikaID { get; set; }
        public int OsebaID { get; set; }
        public int AktivnostUporabnikaStatusID { get; set; }
        public string IP { get; set; }
        public string Opis { get; set; }
        public System.DateTime TS { get; set; }
    
        public virtual AktivnostUporabnikaStatus AktivnostUporabnikaStatus { get; set; }
        public virtual Osebe_OTP Osebe_OTP { get; set; }
    }
}
