//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AktivnostUporabnikaStatus
    {
        public AktivnostUporabnikaStatus()
        {
            this.AktivnostUporabnika = new HashSet<AktivnostUporabnika>();
        }
    
        public int AktivnostUporabnikaStatusID { get; set; }
        public string Koda { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public System.DateTime TS { get; set; }
    
        public virtual ICollection<AktivnostUporabnika> AktivnostUporabnika { get; set; }
    }
}
