//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narocilo
    {
        public Narocilo()
        {
            this.NarociloPozicija = new HashSet<NarociloPozicija>();
        }
    
        public int NarociloID { get; set; }
        public int NarociloStevilka { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public string Relacija { get; set; }
        public Nullable<decimal> KolicinaSkupaj { get; set; }
        public Nullable<int> tsIDOseba { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
    
        public virtual ICollection<NarociloPozicija> NarociloPozicija { get; set; }
    }
}
