//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odpoklic
    {
        public Odpoklic()
        {
            this.LastnaZaloga = new HashSet<LastnaZaloga>();
            this.PrijavaPrevoznika = new HashSet<PrijavaPrevoznika>();
            this.OdpoklicPozicija = new HashSet<OdpoklicPozicija>();
        }
    
        public int OdpoklicID { get; set; }
        public Nullable<int> DobaviteljID { get; set; }
        public Nullable<int> RelacijaID { get; set; }
        public int StatusID { get; set; }
        public Nullable<decimal> CenaPrevoza { get; set; }
        public decimal KolicinaSkupno { get; set; }
        public string Opis { get; set; }
        public Nullable<decimal> PaleteSkupaj { get; set; }
        public string SoferNaziv { get; set; }
        public string Registracija { get; set; }
        public string OdobritevKomentar { get; set; }
        public Nullable<int> tsIDOseba { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> RazpisPozicijaID { get; set; }
        public Nullable<int> OdpoklicStevilka { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DatumNaklada { get; set; }
        public string DobaviteljNaziv { get; set; }
        public string DobaviteljNaslov { get; set; }
        public string DobaviteljPosta { get; set; }
        public string DobaviteljKraj { get; set; }
        public Nullable<bool> DobaviteljUrediTransport { get; set; }
        public string RazlogOdobritveSistem { get; set; }
        public Nullable<bool> LastenPrevoz { get; set; }
        public Nullable<int> TipPrevoza { get; set; }
        public Nullable<int> LastnoSkladisceID { get; set; }
        public Nullable<bool> KupecUrediTransport { get; set; }
        public string Prevozniki { get; set; }
        public Nullable<bool> PovprasevanjePoslanoPrevoznikom { get; set; }
        public Nullable<bool> PrevoznikOddalNajnizjoCeno { get; set; }
        public Nullable<System.DateTime> DatumPosiljanjaMailLogistika { get; set; }
        public string OpombaZaPovprasevnjePrevoznikom { get; set; }
        public Nullable<System.DateTime> P_CreateOrder { get; set; }
        public Nullable<int> P_UnsuccCountCreatePDFPantheon { get; set; }
        public Nullable<System.DateTime> P_LastTSCreatePDFPantheon { get; set; }
        public string P_TransportOrderPDFName { get; set; }
        public string P_TransportOrderPDFDocPath { get; set; }
        public Nullable<System.DateTime> P_GetPDFOrderFile { get; set; }
        public Nullable<System.DateTime> DatumRazklada { get; set; }
        public Nullable<int> P_SendWarningToAmin { get; set; }
        public Nullable<int> ZbirnikTonID { get; set; }
        public Nullable<System.DateTime> ConfirmTS { get; set; }
        public Nullable<decimal> LowestPrice { get; set; }
    
        public virtual ICollection<LastnaZaloga> LastnaZaloga { get; set; }
        public virtual StatusOdpoklica StatusOdpoklica { get; set; }
        public virtual Relacija Relacija { get; set; }
        public virtual TipPrevoza TipPrevoza1 { get; set; }
        public virtual Osebe_OTP Osebe_OTP { get; set; }
        public virtual ICollection<PrijavaPrevoznika> PrijavaPrevoznika { get; set; }
        public virtual Stranka_OTP Stranka_OTP { get; set; }
        public virtual Stranka_OTP Stranka_OTP1 { get; set; }
        public virtual ICollection<OdpoklicPozicija> OdpoklicPozicija { get; set; }
        public virtual ZbirnikTon ZbirnikTon { get; set; }
    }
}
