//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdpoklicKupec
    {
        public OdpoklicKupec()
        {
            this.OdpoklicKupecPozicija = new HashSet<OdpoklicKupecPozicija>();
        }
    
        public int OdpoklicKupecID { get; set; }
        public Nullable<int> RelacijaID { get; set; }
        public int StatusID { get; set; }
        public string StevilkaNarocilnica { get; set; }
        public Nullable<decimal> CenaPrevoza { get; set; }
        public decimal KolicinaSkupno { get; set; }
        public string Opis { get; set; }
        public string SoferNaziv { get; set; }
        public string Registracija { get; set; }
        public string OdobritevKomentar { get; set; }
        public decimal VrednostTransportaSk { get; set; }
        public decimal ProcentTransportaSk { get; set; }
        public string OdgovornaOseba { get; set; }
        public string PodpisPrevoznikNaziv { get; set; }
        public Nullable<int> tsIDOseba { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> OdpoklicStevilkaKupec { get; set; }
        public Nullable<int> UserID { get; set; }
        public string RazlogOdobritveSistem { get; set; }
        public Nullable<int> ZbirnikTonID { get; set; }
        public Nullable<bool> IzdelanaNarocilnica { get; set; }
        public string NarocilnicaXML { get; set; }
        public string PovezaneFaktureXML { get; set; }
        public Nullable<int> OdpoklicKupecStevilka { get; set; }
        public Nullable<int> RazpisPozicijaID { get; set; }
    
        public virtual Osebe_OTP Osebe_OTP { get; set; }
        public virtual RazpisPozicija RazpisPozicija { get; set; }
        public virtual StatusOdpoklica StatusOdpoklica { get; set; }
        public virtual ZbirnikTon ZbirnikTon { get; set; }
        public virtual Relacija Relacija { get; set; }
        public virtual ICollection<OdpoklicKupecPozicija> OdpoklicKupecPozicija { get; set; }
    }
}
