//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdpoklicPozicija
    {
        public int OdpoklicPozicijaID { get; set; }
        public int OdpoklicID { get; set; }
        public string NarociloID { get; set; }
        public int NarociloPozicijaID { get; set; }
        public int TipID { get; set; }
        public decimal Kolicina { get; set; }
        public decimal KolicinaIzNarocila { get; set; }
        public int StatusKolicine { get; set; }
        public string Material { get; set; }
        public Nullable<int> tsIDOseba { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public string OC { get; set; }
        public Nullable<decimal> KolicinaPrevzeta { get; set; }
        public Nullable<decimal> KolicinaRazlika { get; set; }
        public Nullable<decimal> Palete { get; set; }
        public string KupecNaziv { get; set; }
        public Nullable<int> KupecViden { get; set; }
        public Nullable<decimal> TrenutnaZaloga { get; set; }
        public Nullable<decimal> OptimalnaZaloga { get; set; }
        public string TipNaziv { get; set; }
        public string Interno { get; set; }
        public Nullable<decimal> Proizvedeno { get; set; }
        public string MaterialIdent { get; set; }
        public Nullable<decimal> KolicinaOTPPozicijaNarocilnice { get; set; }
        public Nullable<int> ZaporednaStevilka { get; set; }
        public Nullable<System.DateTime> DatumVnosa { get; set; }
        public Nullable<decimal> KolicinaOTP { get; set; }
        public Nullable<bool> StatusPrevzeto { get; set; }
        public string KupecNaslov { get; set; }
        public string KupecPosta { get; set; }
        public string KupecKraj { get; set; }
        public Nullable<bool> OdpoklicIzLastneZaloge { get; set; }
        public Nullable<int> PrvotniOdpoklicPozicijaID { get; set; }
        public Nullable<bool> Split { get; set; }
        public string EnotaMere { get; set; }
        public Nullable<decimal> TransportnaKolicina { get; set; }
        public Nullable<decimal> StPalet { get; set; }
    
        public virtual Odpoklic Odpoklic { get; set; }
    }
}
