//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdpoklicKupecPozicija
    {
        public int OdpoklicKupecPozicijaID { get; set; }
        public int OdpoklicKupecID { get; set; }
        public Nullable<int> TipVnosa { get; set; }
        public string Kljuc { get; set; }
        public Nullable<System.DateTime> DatumVnosa { get; set; }
        public string Valuta { get; set; }
        public string Kupec { get; set; }
        public string Prevzemnik { get; set; }
        public decimal Kolicina { get; set; }
        public Nullable<decimal> Vrednost { get; set; }
        public Nullable<int> ZaporednaStevilka { get; set; }
        public decimal VrednostTransporta { get; set; }
        public Nullable<int> OdpoklicKupecStevilka { get; set; }
        public decimal ProcentTransporta { get; set; }
        public Nullable<int> tsIDOseba { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> Akcija { get; set; }
        public string acKey { get; set; }
    
        public virtual OdpoklicKupec OdpoklicKupec { get; set; }
    }
}
