//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrevzemiView
    {
        public Nullable<System.DateTime> Datum_Prevzema { get; set; }
        public string Dobavitelj { get; set; }
        public string Stevilka_Odpoklica { get; set; }
        public string Ident { get; set; }
        public string Artikel { get; set; }
        public decimal Kolicina_Prevzema { get; set; }
    }
}
