//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrijavaPrevoznika
    {
        public int PrijavaPrevoznikaID { get; set; }
        public int OdpoklicID { get; set; }
        public int PrevoznikID { get; set; }
        public decimal PrvotnaCena { get; set; }
        public Nullable<decimal> PrijavljenaCena { get; set; }
        public System.DateTime DatumNaklada { get; set; }
        public System.DateTime DatumPosiljanjePrijav { get; set; }
        public Nullable<System.DateTime> DatumPrijave { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public string OpombaPrijave { get; set; }
    
        public virtual Odpoklic Odpoklic { get; set; }
        public virtual Stranka_OTP Stranka_OTP { get; set; }
    }
}
