//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Razpis
    {
        public Razpis()
        {
            this.RazpisPozicija = new HashSet<RazpisPozicija>();
        }
    
        public int RazpisID { get; set; }
        public decimal CenaSkupaj { get; set; }
        public System.DateTime DatumRazpisa { get; set; }
        public Nullable<int> tsIDOseba { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public string Naziv { get; set; }
        public Nullable<bool> RazpisKreiran { get; set; }
    
        public virtual ICollection<RazpisPozicija> RazpisPozicija { get; set; }
    }
}
