//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RazpisPozicija
    {
        public int RazpisPozicijaID { get; set; }
        public int RazpisID { get; set; }
        public int StrankaID { get; set; }
        public int RelacijaID { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public Nullable<int> IDOseba { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public string PotDokumenta { get; set; }
        public Nullable<bool> PrevoznikAktualnaCena { get; set; }
    
        public virtual Razpis Razpis { get; set; }
        public virtual Relacija Relacija { get; set; }
        public virtual Stranka_OTP Stranka_OTP { get; set; }
    }
}
