//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RazpisPozicijaSpremembe
    {
        public int RazpisPozicijaSpremembeID { get; set; }
        public int RazpisID { get; set; }
        public int StrankaID { get; set; }
        public int RelacijaID { get; set; }
        public Nullable<decimal> StaraCena { get; set; }
        public Nullable<decimal> NovaCena { get; set; }
        public int IDVnosOseba { get; set; }
        public Nullable<System.DateTime> VnosTS { get; set; }
        public int IDSpremembeOseba { get; set; }
        public Nullable<System.DateTime> SpremembeTS { get; set; }
        public int ZbirnikTonID { get; set; }
    
        public virtual Razpis Razpis { get; set; }
        public virtual Relacija Relacija { get; set; }
        public virtual Stranka_OTP Stranka_OTP { get; set; }
        public virtual ZbirnikTon ZbirnikTon { get; set; }
        public virtual Osebe_OTP Osebe_OTP { get; set; }
        public virtual Osebe_OTP Osebe_OTP1 { get; set; }
    }
}
