//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relacija
    {
        public Relacija()
        {
            this.RazpisPozicija = new HashSet<RazpisPozicija>();
            this.Odpoklic = new HashSet<Odpoklic>();
            this.RazpisPozicijaSpremembe = new HashSet<RazpisPozicijaSpremembe>();
            this.OdpoklicKupec = new HashSet<OdpoklicKupec>();
        }
    
        public int RelacijaID { get; set; }
        public string Koda { get; set; }
        public string Naziv { get; set; }
        public decimal Dolzina { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public string Opomba { get; set; }
    
        public virtual ICollection<RazpisPozicija> RazpisPozicija { get; set; }
        public virtual ICollection<Odpoklic> Odpoklic { get; set; }
        public virtual ICollection<RazpisPozicijaSpremembe> RazpisPozicijaSpremembe { get; set; }
        public virtual ICollection<OdpoklicKupec> OdpoklicKupec { get; set; }
    }
}
