//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusOdpoklica
    {
        public StatusOdpoklica()
        {
            this.Odpoklic = new HashSet<Odpoklic>();
            this.OdpoklicKupec = new HashSet<OdpoklicKupec>();
        }
    
        public int StatusOdpoklicaID { get; set; }
        public string Koda { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public Nullable<int> tsIDOseba { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
    
        public virtual ICollection<Odpoklic> Odpoklic { get; set; }
        public virtual ICollection<OdpoklicKupec> OdpoklicKupec { get; set; }
    }
}
