//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stranka_OTP
    {
        public Stranka_OTP()
        {
            this.LastnaZaloga = new HashSet<LastnaZaloga>();
            this.Odpoklic = new HashSet<Odpoklic>();
            this.Odpoklic1 = new HashSet<Odpoklic>();
            this.PrijavaPrevoznika = new HashSet<PrijavaPrevoznika>();
            this.RazpisPozicija = new HashSet<RazpisPozicija>();
            this.StrankaZaposleni_OTP = new HashSet<StrankaZaposleni_OTP>();
            this.KontaktneOsebe_OTP = new HashSet<KontaktneOsebe_OTP>();
        }
    
        public int idStranka { get; set; }
        public string KodaStranke { get; set; }
        public int TipID { get; set; }
        public string NazivPrvi { get; set; }
        public string NazivDrugi { get; set; }
        public string Naslov { get; set; }
        public string StevPoste { get; set; }
        public string NazivPoste { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string FAX { get; set; }
        public string InternetniNalov { get; set; }
        public string KontaktnaOseba { get; set; }
        public string RokPlacila { get; set; }
        public string TRR { get; set; }
        public string DavcnaStev { get; set; }
        public string MaticnaStev { get; set; }
        public string RangStranke { get; set; }
        public string StatusDomacTuji { get; set; }
        public string Zavezanec_DA_NE { get; set; }
        public string IdentifikacijskaStev { get; set; }
        public string Clan_EU { get; set; }
        public string BIC { get; set; }
        public string KodaPlacila { get; set; }
        public string StatusKupecDobavitelj { get; set; }
        public string DrzavaStranke { get; set; }
        public string Neaktivna { get; set; }
        public Nullable<int> GenerirajERacun { get; set; }
        public Nullable<int> JavniZavod { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
        public Nullable<int> TipPrevoza { get; set; }
        public Nullable<int> Activity { get; set; }
        public Nullable<int> JezikID { get; set; }
    
        public virtual ICollection<LastnaZaloga> LastnaZaloga { get; set; }
        public virtual ICollection<Odpoklic> Odpoklic { get; set; }
        public virtual ICollection<Odpoklic> Odpoklic1 { get; set; }
        public virtual ICollection<PrijavaPrevoznika> PrijavaPrevoznika { get; set; }
        public virtual ICollection<RazpisPozicija> RazpisPozicija { get; set; }
        public virtual TipStranka TipStranka { get; set; }
        public virtual ICollection<StrankaZaposleni_OTP> StrankaZaposleni_OTP { get; set; }
        public virtual TipPrevoza TipPrevoza1 { get; set; }
        public virtual Jeziki Jeziki { get; set; }
        public virtual ICollection<KontaktneOsebe_OTP> KontaktneOsebe_OTP { get; set; }
    }
}
