//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrankaZaposleni_OTP
    {
        public int idStrankaOsebe { get; set; }
        public Nullable<int> idStranka { get; set; }
        public Nullable<int> idOsebe { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
    
        public virtual Osebe_OTP Osebe_OTP { get; set; }
        public virtual Stranka_OTP Stranka_OTP { get; set; }
    }
}
