//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainOTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipPrevoza
    {
        public TipPrevoza()
        {
            this.Odpoklic = new HashSet<Odpoklic>();
            this.Stranka_OTP = new HashSet<Stranka_OTP>();
        }
    
        public int TipPrevozaID { get; set; }
        public string Koda { get; set; }
        public string Naziv { get; set; }
        public string Opombe { get; set; }
        public Nullable<decimal> DovoljenaTeza { get; set; }
        public Nullable<bool> ShranjevanjePozicij { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDPrijave { get; set; }
    
        public virtual ICollection<Odpoklic> Odpoklic { get; set; }
        public virtual ICollection<Stranka_OTP> Stranka_OTP { get; set; }
    }
}
