//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainNOZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarociloOptimalnihZalog
    {
        public NarociloOptimalnihZalog()
        {
            this.NarociloOptimalnihZalogPozicija = new HashSet<NarociloOptimalnihZalogPozicija>();
        }
    
        public int NarociloOptimalnihZalogID { get; set; }
        public int StrankaID { get; set; }
        public int StatusID { get; set; }
        public string Naziv { get; set; }
        public string NarociloOptimalnihZalogStevilka { get; set; }
        public string NarociloID_P { get; set; }
        public Nullable<System.DateTime> DatumOddaje { get; set; }
        public decimal Kolicina { get; set; }
        public string Opombe { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
        public Nullable<System.DateTime> tsUpdate { get; set; }
        public Nullable<int> tsUpdateUserID { get; set; }
        public string PotDokumenta { get; set; }
        public Nullable<int> NarociloOddal { get; set; }
    
        public virtual Osebe_NOZ Osebe_NOZ { get; set; }
        public virtual Stranka_NOZ Stranka_NOZ { get; set; }
        public virtual ICollection<NarociloOptimalnihZalogPozicija> NarociloOptimalnihZalogPozicija { get; set; }
        public virtual StatusNarocilaOptimalnihZalog StatusNarocilaOptimalnihZalog { get; set; }
    }
}
