//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainNOZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osebe_NOZ
    {
        public Osebe_NOZ()
        {
            this.OsebeNadrejeni_NOZ = new HashSet<OsebeNadrejeni_NOZ>();
            this.OsebeNadrejeni_NOZ1 = new HashSet<OsebeNadrejeni_NOZ>();
            this.StrankaZaposleni_NOZ = new HashSet<StrankaZaposleni_NOZ>();
            this.SystemEmailMessage_NOZ = new HashSet<SystemEmailMessage_NOZ>();
            this.NarociloOptimalnihZalog = new HashSet<NarociloOptimalnihZalog>();
        }
    
        public int OsebaID { get; set; }
        public int VlogaID { get; set; }
        public string Ime { get; set; }
        public string Priimek { get; set; }
        public string Naslov { get; set; }
        public Nullable<System.DateTime> DatumRojstva { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DatumZaposlitve { get; set; }
        public string UporabniskoIme { get; set; }
        public string Geslo { get; set; }
        public string TelefonGSM { get; set; }
        public Nullable<int> Zunanji { get; set; }
        public string DelovnoMesto { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDOsebe { get; set; }
        public Nullable<System.DateTime> tsUpdate { get; set; }
        public Nullable<int> tsUpdateUserID { get; set; }
        public Nullable<bool> NOZDostop { get; set; }
        public string Podpis { get; set; }
        public string PantheonUsrID { get; set; }
    
        public virtual ICollection<OsebeNadrejeni_NOZ> OsebeNadrejeni_NOZ { get; set; }
        public virtual ICollection<OsebeNadrejeni_NOZ> OsebeNadrejeni_NOZ1 { get; set; }
        public virtual ICollection<StrankaZaposleni_NOZ> StrankaZaposleni_NOZ { get; set; }
        public virtual ICollection<SystemEmailMessage_NOZ> SystemEmailMessage_NOZ { get; set; }
        public virtual Vloga_NOZ Vloga_NOZ { get; set; }
        public virtual ICollection<NarociloOptimalnihZalog> NarociloOptimalnihZalog { get; set; }
    }
}
