//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainNOZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class OsebeNadrejeni_NOZ
    {
        public int OsebeNadrejeniID { get; set; }
        public int OsebaID { get; set; }
        public int NadrejeniID { get; set; }
        public string Opomba { get; set; }
        public Nullable<System.DateTime> ts { get; set; }
        public Nullable<int> tsIDosebe { get; set; }
        public Nullable<System.DateTime> tsUpdate { get; set; }
        public Nullable<int> tsUpdateUserID { get; set; }
    
        public virtual Osebe_NOZ Osebe_NOZ { get; set; }
        public virtual Osebe_NOZ Osebe_NOZ1 { get; set; }
    }
}
