//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebService.DomainDW
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFlow_Skupno
    {
        public int CashFlowSkupnoID { get; set; }
        public Nullable<System.DateTime> DatumPlana { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Vrsta { get; set; }
        public decimal PlacilaKupcev { get; set; }
        public decimal PlacilaAvansov { get; set; }
        public decimal PlacilaDobaviteljskiFaktoring { get; set; }
        public decimal PlacilaDobaviteljem { get; set; }
        public decimal PlacilaCassaSconto { get; set; }
        public Nullable<decimal> PlacilaOdkupov { get; set; }
        public Nullable<decimal> PlacilaOdkupovHR { get; set; }
        public Nullable<decimal> PlacilaDDV { get; set; }
        public Nullable<decimal> PlacilaPlace { get; set; }
        public Nullable<decimal> PlacilaKredit { get; set; }
        public Nullable<decimal> PlacilaLeasing { get; set; }
        public Nullable<decimal> PlacilaCassaScontoRocni { get; set; }
    }
}
